name: CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    uses: yavorfingarov/Workflows/.github/workflows/build.yml@master
    with:
      unit-tests-path: ./tests/Reprise.UnitTests
      status-gist-id: 552110af4a546bfef6adfd60e60163c3
    secrets: inherit

  publish:
    name: Publish
    needs: build
    if: ${{ needs.build.outputs.run-next == 'true' }}
    uses: yavorfingarov/Workflows/.github/workflows/publish-nuget.yml@master
    with:
      csproj-path: ./src/Reprise/Reprise.csproj
    secrets: inherit
