name: CI

on:
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: 7.0.x
  UNIT_TESTS_PATH: ./tests/Reprise.UnitTests

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Analyze code
        run: dotnet format --no-restore --verify-no-changes --severity info
      - name: Build
        run: dotnet build --no-restore
      - name: Run unit tests
        run: dotnet test --no-build --filter UnitTests --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: Run integration tests
        run: dotnet test --no-build --filter IntegrationTests
      - name: Generate test coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.15
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: TestCoverageReport
          reporttypes: 'Html'
      - name: Set up Stryker
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-stryker
      - name: Run mutation tests
        run: dotnet tool run dotnet-stryker --config-file stryker-config.yaml --reporter "html"
        working-directory: ${{ env.UNIT_TESTS_PATH }}
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v3
        with:
          name: CoverageReport      
          path: |
            ./TestCoverageReport/
            **/StrykerOutput/*/reports/mutation-report.html
